export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#f1eeff",
        "on-background": "#131b2e",
        "inverse-primary": "#b4c5ff",
        "secondary-fixed": "#d5e3fc",
        "on-primary-container": "#eeefff",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-container": "#d5e3fc",
        "on-primary": "#ffffff",
        "surface": "#faf8ff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#3a485b",
        "tertiary-fixed": "#e1e0ff",
        "error-container": "#ffdad6",
        "surface-container-low": "#f2f3ff",
        "on-secondary-fixed": "#0d1c2e",
        "primary": "#004ac6",
        "secondary": "#515f74",
        "primary-container": "#2563eb",
        "on-surface-variant": "#434655",
        "on-primary-fixed": "#00174b",
        "inverse-on-surface": "#eef0ff",
        "surface-container-high": "#e2e7ff",
        "on-secondary-container": "#57657a",
        "primary-fixed-dim": "#b4c5ff",
        "surface-tint": "#0053db",
        "primary-fixed": "#dbe1ff",
        "secondary-fixed-dim": "#b9c7df",
        "on-tertiary-fixed": "#07006c",
        "tertiary-fixed-dim": "#c0c1ff",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c3c6d7",
        "tertiary": "#3e3fcc",
        "on-surface": "#131b2e",
        "on-secondary": "#ffffff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "tertiary-container": "#585be6",
        "background": "#faf8ff",
        "surface-variant": "#dae2fd",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface-container": "#eaedff",
        "inverse-surface": "#283044",
        "surface-container-highest": "#dae2fd",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "outline": "#737686"
      },
      spacing: {
        "space-xl": "1.25rem",
        "layout-sidebar-collapsed": "4rem",
        "space-sm": "0.5rem",
        "layout-header": "3.25rem",
        "table-row-height": "2.5rem",
        "space-md": "0.75rem",
        "space-3xl": "2rem",
        "space-lg": "1rem",
        "layout-sidebar": "16rem",
        "space-xs": "0.25rem",
        "space-2xl": "1.5rem",
        "space-4xl": "2.5rem",
        "table-row-compact": "2rem",
        "space-2xs": "0.125rem"
      },
      fontFamily: {
        "body-md": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-md": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "caption": ["Geist", "sans-serif"]
      },
      fontSize: {
        "body-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "code-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "label-md": ["13px", { "lineHeight": "16px", "letterSpacing": "0em", "fontWeight": "500" }],
        "body-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.025em", "fontWeight": "600" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["15px", { "lineHeight": "24px", "letterSpacing": "-0.005em", "fontWeight": "400" }],
        "caption": ["11px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
